### ISSUE TITLE
The result is a wrong sum of tables in headers and footers

### ISSUE THREAD

**Issue by nav-fess** [onlyoffice-testing-robot/ooxml_object_counter#13]
The sum of tables in the headers is 1.

Expected Result:
----------------
All tables from headers and footers are summarized

Actual result
----------------
Summarize only one table in headers and footers

[projet 2 séquence 3  3ème AP.docx](https://github.com/onlyoffice-testing-robot/ooxml_object_counter/files/1737232/projet.2.sequence.3.3eme.AP.docx)
[XpertdocOnlineDemoEn.docx](https://github.com/onlyoffice-testing-robot/ooxml_object_counter/files/1737233/XpertdocOnlineDemoEn.docx)
[Windows Phone (50p).docx](https://github.com/onlyoffice-testing-robot/ooxml_object_counter/files/1739796/Windows.Phone.50p.docx)

**Comment by ShockwaveNN** [comment]
This is correct behavior. Same table for repeated header presented only once in docx file
