### ISSUE TITLE
Error on parsing file in function "table"

### ISSUE THREAD

**Issue by nav-fess** [onlyoffice-testing-robot/ooxml_object_counter#18]
Add table into Rich Text Content Control

Expected Result:
--------------------------------
The test counted the number of tables

Actual result:
--------------------------------
test not passed. Error:
NoMethodError: undefined method `parent' for OoxmlParser::DocumentStructure:Class

[--- Стандартное_резюме.docx](https://github.com/onlyoffice-testing-robot/ooxml_object_counter/files/1757731/---._.docx)

**Comment by ShockwaveNN** [comment]
Fixed in https://github.com/ONLYOFFICE/ooxml_parser/pull/463
