### ISSUE TITLE
All tables in the footer or header are counted as one

### ISSUE THREAD

**Issue by nav-fess** [onlyoffice-testing-robot/ooxml_object_counter#19]
Add table into footer or header

Expected Result:
The test counted the number of all tables

Actual result:
The test counted only one table in the footer or header

[--- Удивительная история рождения MS-Dos.docx](https://github.com/onlyoffice-testing-robot/ooxml_object_counter/files/1757998/---.MS-Dos.docx)

[--- Феномен западнизма - копия.docx](https://github.com/onlyoffice-testing-robot/ooxml_object_counter/files/1758062/---.-.docx)

[(2) projet 3 séquence 3   3ème AP.docx](https://github.com/onlyoffice-testing-robot/ooxml_object_counter/files/1759012/2.projet.3.sequence.3.3eme.AP.docx)

**Comment by nav-fess** [comment]
Clone  issues 3

**Comment by ShockwaveNN** [comment]
Duplicate of #13
