### ISSUE TITLE
The parser did not find the table in the footer

### ISSUE THREAD

**Issue by nav-fess** [onlyoffice-testing-robot/ooxml_object_counter#20]
Add table into footer and add table in list

Expected Result:
--------------------------------
The test counted the number of all tables

Actual result:
--------------------------------
The test counted only tables in  list

[2.Intitule.du.proje1.-.docx](https://github.com/onlyoffice-testing-robot/ooxml_object_counter/files/1762102/2.Intitule.du.proje1.-.docx)

**Comment by ShockwaveNN** [comment]
Count of tables is 16 like in structure, everything seem right
