### ISSUE TITLE
Error on parsing file in function "table_count_paragraph". 

### ISSUE THREAD

**Issue by nav-fess** [onlyoffice-testing-robot/ooxml_object_counter#7]
Add equation after void table.

Expected Result
test passed

Actual result
test not passed. Error:
NoMethodError: undefined method `alternate_content' for #<OoxmlParser::DocxFormula:0x000000023481c0>

[Грищенко.docx](https://github.com/onlyoffice-testing-robot/ooxml_object_counter/files/1711661/default.docx)

**Comment by ShockwaveNN** [comment]
Fixed in #6
